export const ADD_INGREDIANT = 'ADD_INGREDIANT';
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT';
export const INIT_INGREDIANTS = 'INIT_INGREDIANTS';
export const INSERT_INGREDIANTS_LIST = 'INSERT_INGREDIANTS_LIST';
export const FETCH_INGREDIANTS_ERROR = 'FETCH_INGREDIANTS_ERROR';

